# Generated by Django 3.1.2 on 2020-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('category', 'Category'), ('subcategory', 'Subcategory'), ('tag', 'Tag')], max_length=20),
        ),
    ]
