# Generated by Django 3.0.8 on 2020-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
