# Generated by Django 3.1.5 on 2021-02-15 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210215_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
