# Generated by Django 3.1.5 on 2021-02-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_shorturl_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='account_type',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
