# Generated by Django 3.1.5 on 2021-02-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_shorturl_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='account_type',
        ),
    ]
