# Generated by Django 3.1.5 on 2021-02-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0009_auto_20210215_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='expire_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
